name: CloudFormation Guard validate

on:
  push:

jobs:
  guard:
    runs-on: ubuntu-latest
    name: CloudFormation Guard validate
    steps:
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: './rules'
          data: './no_data'